### ISSUE TITLE
Hello ayust

### ISSUE THREAD

**Issue by Matterall373** [ayust/alpha-guide#10]
Really good work.  Thanks for helping EVE players. This reminds me of the old school guides people used to make - things I read over and over agian.  

Is there a good way to get in touch with you.  I'd like to feature your work on an EVE show/podcast (Talking In Stations) or on Imperium news.

you can reach me on skype @matterall373 or at this discord https://discord.gg/hKhxq4m

Thanks very much

**Comment by ayust** [comment]
DMing on Twitter works fine, https://twitter.com/aiiane
