### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by ka5huk3n** [ayust/alpha-guide#11]
Greetings!
I'm currently working on Russian translation for this guide here:
https://github.com/ka5huk3n/alpha-guide

I followed translation guide and created translated-ru branch (had to recreate existing fork for that..)

**Comment by ka5huk3n** [comment]
There also related issue with Cyrillic fonts in basic Learn theme.
You can notice how most of (but not all!) the custom fonts that don't have Cyrillic characters failsafe to Arial or another default font.
Examples: 
https://counseller-elephant-68822.netlify.com/start/  (notice how АЛЬФА is written)
https://counseller-elephant-68822.netlify.com/start/welcome/  (Eve Online is different from other text)

I've used css overrides for that (but maybe this is not the right way now)
h1 {
    font-family: "Georgia", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
  }
body {
    font-family: "Georgia", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
  }
#chapter h3 { font-family: "Tahoma", "Arial", sans-serif;
  }

Default Georgia font will look great with Cyrrilic text in RU guide and it's web safe.

**Comment by ayust** [comment]
Using a CSS override is fine to address the font issue. You may also want to translate the title (in `layouts/partials/logo.html`) that's displayed in the upper-left.

**Comment by ka5huk3n** [comment]
Thanks, already on it.
I suppose it's ok to change static content too? Like some screenshots and wtd image (we have localized pic already).
That's not an urgent matter, I'll save this for the last.

**Comment by ayust** [comment]
Yes, it's fine to localize the static content as well. Please however check to make sure that the localized versions of the static content have similar (or smaller) file sizes to the original versions (sometimes re-saving an image results in a massively larger image due to different compression options).

**Comment by ayust** [comment]
Cleaning up old issues
