### ISSUE TITLE
Suggestions: Warning about tutorial issues, Suggest you make submit it to CCP as a fansite.

### ISSUE THREAD

**Issue by samuel-the-terrible** [ayust/alpha-guide#16]
Hi there, I did not want to attempt to edit your document and propose changes in anyway. I did have a couple of suggestions:
a) On your prerequisites page, you list that pilots should have completed the tutorial, you also have some FAQs listed. 

The Tutorial is very susceptible to breaking if players do anything before instructed or not exactly as instructed so I thought it may be worth you putting some form of alert class warning up for people to see.

b) If you have not already done so you should consider submitting this site to CCP as an official fan-site. If for no other reason, if successful you will get listed here: https://community.eveonline.com/community/fansites/ - I believe that it may draw the attention of people to your site.

If you have not already done so, you can go to this page, for more information: https://community.eveonline.com/community/fansites/submit/

Thank you for your time, and a great resource.

**Comment by ayust** [comment]
The guide is already linked from the Rookie Help channel ingame. I think that's enough linkage from CCP. :) Thanks for the suggestion, though!
