### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by miguelkreilly** [ayust/alpha-guide#5]
Hi, nice job!

Do you think you can add a spanish version? We can give you the translated texts.

**Comment by ayust** [comment]
If you're willing to translate that might be possible - how familiar are you with Git?

**Comment by miguelkreilly** [comment]
Nothing, xD. Must I raise a fork and just translate in there?

**Comment by ayust** [comment]
That's a good start, I can handle the branching once you've done the translations.

**Comment by ayust** [comment]
I've written a guide for those generally wanting to translate the Guide:
https://github.com/ayust/alpha-guide/wiki/Translating-the-Guide

That said, since you mentioned not being familiar with Git, I'm happy to work out other options.

**Comment by miguelkreilly** [comment]
Thanks! this is a crazy job week for me, but I hope I can translate it during the weekend. Thanks for the guide! I had been trying Git and I surely can do it, but if I can't I can send you the .md files by email or something.

**Comment by miguelkreilly** [comment]
I have some manuals in spanish for carrer misions, sister of eve arc and things like this, do you mind if I include links to them in the spanish translation?

**Comment by ayust** [comment]
The Guide tries to strike a balance between providing enough information to make a difference without overwhelming the player with too much information. Given that most of the existing external links are in English, feel free to replace them with links to appropriate language resources that serve the same purpose.

For adding new links to resources that aren't equivalent to what's in the Guide already, exercise your best judgment as to whether it fits that balance - try not to just blindly link to a large swath of guides, but if something really would benefit from an appropriate language guide, that's okay.

**Comment by ayust** [comment]
Cleaning up old issues
