### ISSUE TITLE
Osmium Fits

### ISSUE THREAD

**Issue by rilofree** [ayust/alpha-guide#60]
Hello,

I found your Alpha-Guide to be very helpful. Especially the "how to fit ships well" page. 

FYI, you may be aware that Osmium is no longer a thing. There is a link to a private Osmium fit for the Improved Cormorant at the end of your "how to fit ships well" page which is now dead and does no show up on Wayback.org either.

Thank you for a very thorough guide. I found it very useful.

Richard Free

**Comment by ayust** [comment]
Looks like that page got missed when we replaced the rest of the Osmium links in other parts of the guide.

**Comment by ayust** [comment]
Addressed in a88d8061366fc567ac98e4785dc6a9e65b7456cd
