### ISSUE TITLE
Hi guys, I've been busy, it may be useful xD

### ISSUE THREAD

**Issue by YepharNahtepa** [ayust/alpha-guide#66]
Hi there, I just saw a link to your resource, well done, it is great.
I have played Eve 11 years and over the last year have been making videos, mostly using Alpha alts, to show new players how to make isk, understand game concepts and develop as players. 
I will certainly be linking to this from my vids etc, Feel free to link / mention my channel if you think it may help so peeps, but that is your decision :)

Here's a couple of examples:

Alpha Does the Hunt, Blaster Catalyst Including finding the capsules with D Scan https://youtu.be/93lzFoaI6Y0
Alpha Through the Wormhole. inc mobile depot, implants and murder https://youtu.be/pBpVlUPxyZY
Alpha Goes to Low Sec Basic Gallente Ratting (and 80mil kill with 2 mil Cat) https://youtu.be/CqU8-XfaL90

Keep up the good work, let me know if I can ever lend a hand!

Fly Brave o7
'Eveing Is Believing'
Mark W 
( ThinTrash / Anne Thraxx )
daddex2000.gmail.com

**Comment by ayust** [comment]
Cleaning up old issues
