### ISSUE TITLE
Tutorial videos no longer under F12

### ISSUE THREAD

**Issue by Drakooth** [ayust/alpha-guide#76]
I was following along the guide, and during the exploration career part, i was suggested to watch some tutorial videos.

> The scanning interfaces can be a little hard to understand without seeing them in operation. Thankfully, EVE has a set of built-in video tutorials for how to use the scanning interfaces. To view them, press F12 to open the “Help” window, then select the “Tutorial Videos” tab. Scroll down to the “Exploration” subsection (click to expand it). Then watch the following videos

However the tutorial videos are no longer under the F12 menu.

**Comment by ayust** [comment]
Yep, it looks like they moved the links to those videos to the help articles that are part of the Customer Service knowledge base at this point.

You can find them by clicking "Get Help" and then browsing the knowledge base; some of the pages under "Gameplay and Features" will have tutorial videos embedded (for instance, the scanning one is here: https://support.eveonline.com/hc/en-us/articles/203209902-Scanning).

**Comment by ayust** [comment]
Fixed in c03d70521719a1a55f12a4bdfe4f4b7371ffe0e5 and 93315097534dd494373387deccf0835116c5b3b0.

**Comment by ayust** [comment]
Thanks for reporting the problem!
