### ISSUE TITLE
Tristan improved fit module name has changed

### ISSUE THREAD

**Issue by DocSawage** [ayust/alpha-guide#81]
Hi there, I was having trouble locating the Small Electrochemical Capacitor Booster I for the improved Tristan fit; I found it was renamed to Small F-RX Compact Capacitor Booster in March 2020.

Thanks for your guide, it has been very helpful to me.

**Comment by ayust** [comment]
Yeah, this is a specific instance of #73 - a bunch of modules got renamed a while back. I'll fix this particular one, but there are probably more that also need fixing.
